language: python

python:

  - "2.7"
  - "3.5"
  - "3.6"
  
cache: pip

install:
 - pip install --upgrade pip
 - pip install -r requirements.txt
 
 env:
  - FLASK_VERSION=1.0.2

script:
  - python3 -m pytest --cov=app
  - coveralls

after_success:
  - coveralls
